spring.application.name=MLService
server.port=9004

logging.level.root=ERROR

spring.kafka.consumer.group-id=mlGroup
spring.kafka.bootstrap-servers=localhost:9092

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:1b